version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:sysadmin@postgres:5432/barbabrutal
    networks:
      - barbabrutal-network

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - barbabrutal-network

  mobile:
    build:
      context: ./apps/mobile
    ports:
      - "8081:8081"
    networks:
      - barbabrutal-network

  postgres:
    image: postgres:15
    restart: always
    container_name: barbabrutal_database
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=barbabrutal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sysadmin
    networks:
      - barbabrutal-network
    volumes:
      - barbabrutal:/var/lib/postgresql/data

networks:
  barbabrutal-network:
    driver: bridge

volumes:
  barbabrutal:
