GET http://localhost:3001/servico

###
GET http://localhost:3001/profissional

###
POST http://localhost:3001/usuario/login
Content-Type: application/json

{
    "email": "pedroreckel90@gmail.com",
    "senha": "*xpEvanete2001"
}

###
POST http://localhost:3001/usuario/registrar
Content-Type: application/json

{
    "nome": "Kathya Tesourada",
    "email": "kathya@barbabrutal.app",
    "senha": "#Senha123",
    "telefone": "11999999999"
}

###
POST http://localhost:3001/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IlBlZHJvIFJlY2tlbCBSb2JlcnRlIiwiZW1haWwiOiJwZWRyb3JlY2tlbDkwQGdtYWlsLmNvbSIsInRlbGVmb25lIjoiMjc5OTgxNDMxOTEiLCJiYXJiZWlybyI6ZmFsc2UsImlhdCI6MTcyMzY3ODU0MiwiZXhwIjoxNzI0OTc0NTQyfQ.mnLZ-YQDWrYdVeKeUraPrgzK1lRpxjEyjIpznDmv7mE
Content-Type: application/json

{
    "data": "2024-08-15T13:00:00.000Z",
    "usuario": { "id": 1 },
    "profissional": { "id": 1 },
    "servicos": [
        { "id": 1 }, 
        { "id": 2 },
        { "id": 3 }
    ]
}